'use client'

import React from 'react'
import { Col, Container, Image } from 'react-bootstrap'
import { Tab, Tabs, TabList, TabPanel } from 'react-tabs';

import '../ourwork.css'


const KitchenContent = () => {
    return (
        <>
            <Container fluid style={{ background: '#e0e9d3' }} >
                <Container className='text-center p-0 py-5'>
                    <p>“There was a time when we had to spend a lot of money to buy vegetables,” says farmer Rameshappa’s wife. “After we started growing them in our backyard, we not only eat nutritious meals, we also do not spend money,” she adds.</p>


                    <Tabs>
                        <TabList>
                            <Tab>Kitchen Gardens</Tab>
                            <Tab>Community Gardens</Tab>
                        </TabList>

                        <TabPanel>
                            <Col className="text-center w-100">
                                <p>GREEN has helped set up over 950 kitchen gardens throughout Karnataka by providing farmers with resources and training in vegetable cultivation methods that allow them to make the most use of limited space. These kitchen gardens greatly enrich the nutrient intake of families and strengthen their food security, making farmers independent from rising inflation rates and fluctuating market prices. They are an extremely reliable source of vegetables that may have been otherwise unaffordable to families.</p>
                                <Image src='/our-work/kitche-community/kitchen_garden_tab_img.png' alt='' width="70%" />
                            </Col>
                        </TabPanel>
                        <TabPanel>
                            <Col className="text-center w-100">
                                <p>GREEN also enables the setting up of community gardens where all members in a community contribute to the maintenance of a common garden. These act as in-situ conservation sites for vegetable varieties. Income is generated by marketing the seeds and vegetables grown. These gardens especially help landless members of the community as the produce is also shared among them.</p>
                                <Image src='/our-work/kitche-community/community_gardens_tab_img.png' alt='' width="70%" />
                            </Col>
                        </TabPanel>
                    </Tabs>
                </Container>
            </Container>

        </>
    )
}

export default KitchenContent