name: Build & Deploy

on:
  push:
    branches: 
     - main
     
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: greenfoundation Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build # Adjust if you have a build step

      - name: Deploy to server
        uses: webfactory/ssh-action@v0.7.1
        with:
          host: ${{ secrets.SSH_HOST }} # Your server's IP address
          username: ${{ secrets.SSH_USERNAME }} # Your server's username
          key: ${{ secrets.SSH_KEY }} # Your server's SSH private key
          passphrase: ${{ secrets.SSH_PASS }} # Your server's SSH key passphrase (if applicable)
          script: |
            cd /home/react-staging/ivistaz/
            git pull origin main
            npm install
            npm run build
            pm2 restart greenfoundation || pm2 start npm --name "greenfoundation" -- start
