name: Build & Deploy

on:
  push:
    branches:
     - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          host: ${{ secrets.SSH_HOST }} # Your server's IP address
          username: ${{ secrets.SSH_USERNAME }} # Your server's username
          key: ${{ secrets.SSH_KEY }} # Your server's SSH private key
          passphrase: ${{ secrets.SSH_PASS }} # Your server's SSH key passphrase (if applicable)
      - name: SSH Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/react-staging/ivistaz/greenfoundation
            git pull origin main
            npm install
            npm run build
