name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to the server
        run: |
          rsync -avz --exclude='.git' --exclude='node_modules' ./ root@159.89.168.108:/home/react-staging/ivistaz/greenfoundation

      - name: Install dependencies
        run: |
          ssh root@159.89.168.108 "cd /home/react-staging/ivistaz/greenfoundation && npm install"

      - name: Restart application
        run: |
          ssh root@159.89.168.108 "pm2 restart greenfoundation"
